### ISSUE TITLE
Add Sections

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [elenajp/elenajp#3]
Hey! You can start adding following section and also keep on improving
- About yourself
- What you love and what you do
- Your current project / what you are currently learning
- Some gif's, stats, etc
- Take a look at [this](https://awesomegithubprofile.tech/) to make your own customized readme. 
- Hope that helps, Keep collaborating and contributing :heart:

**Comment by elenajp** [comment]
Prefect, thanks @kaiwalyakoparkar some great points and I appreciate the link to look at examples to give me some inspiration

**Comment by kaiwalyakoparkar** [comment]
Yup, they this website is very good. You can select the tags and customize your own readme profile. with the components in the example itself. Happy to help :heart:

**Comment by kaiwalyakoparkar** [comment]
Your profile looks cool now :sunglasses:

**Comment by elenajp** [comment]
Thank you! It is definitely an improvement but I still need to add more to it 🤩 
I am so grateful for attending the live review session with Eddie and all of you guys, otherwise I don't know when I would have made a start on my GitHub profile!

**Comment by kaiwalyakoparkar** [comment]
Did you join EddieHub discord and EddieHub GitHub org?

**Comment by elenajp** [comment]
yes I did 😀

**Comment by kaiwalyakoparkar** [comment]
Did you made your profile public? coz it is not showing on your profile

**Comment by kaiwalyakoparkar** [comment]
I can't find your profile
![image](https://user-images.githubusercontent.com/53310847/117321449-c18f4f00-aeaa-11eb-92de-61e66c69913b.png)

**Comment by elenajp** [comment]
<img width="972" alt="Screenshot 2021-05-07 at 08 03 31" src="https://user-images.githubusercontent.com/53368353/117404834-e9160400-af0a-11eb-96e0-4f705ad6d16e.png">

Yeah it is already set to public so I don't understand why you can't find it. I will check over the settings and see if I am missing anything. By the way thanks a lot for highlighting this, I would have never known otherwise! 💛

**Comment by elenajp** [comment]
ah no wait, that was my profile repo which is public. For EddieHub I see I am not actually a member and I see that I have to be invited by the admin I believe 🧐

**Comment by kaiwalyakoparkar** [comment]
- Click [here](https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.md&title=Please+invite+me+to+the+GitHub+Community+Organization)
- Fill out the details on the issue template and submit
- You will receive an invitation immediately. Click on the link and accept the invitation (The invitation link may come to email as well so keep an eye on it as well)
- Make sure you go [here](https://github.com/orgs/EddieHubCommunity/people), search your name and make the visibility public so that it shows up on your profile

**Comment by elenajp** [comment]
@kaiwalyakoparkar you are awesome! Thanks a lot! I have submitted the issue 🤩

**Comment by kaiwalyakoparkar** [comment]
Yay! you are in EddieHub officially. If you have not already. Drop-in hi in the general channel on discord
